### ISSUE TITLE
It's the LWR3

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/kuka_lwr4_description#1]

**Comment by christian-rauch** [comment]
Why does the label say it's a KUKA LBR IV?
![img_20170715_152916](https://user-images.githubusercontent.com/8226248/44420404-bf0f2e80-a575-11e8-9f89-e7d118144bff.jpg)

**Comment by wxmerkt** [comment]
It is an in-between version as it's early/prototype, cf.
![image](https://user-images.githubusercontent.com/1664508/44425422-baea0d80-a583-11e8-84d9-ea5aaedb9a34.png)

So some of the documents and descriptions online for the released version 4 may or actually do not match this robot - e.g. I think (but not 100% certain) we once discovered slight differences in kinematics.

This was good though - going to check the documents made clear we accidentally added peripherals to recycling during clear-out and we could rectify it in time :-)

**Comment by christian-rauch** [comment]
Good to know. I guess it is based on: https://www.dlr.de/rm/en/desktopdefault.aspx/tabid-11706/

Should we rename the repo to `kuka_lwr3_description` then? (or maybe `kuka_lwr3.5_description` :smiley:)

I would stick with `kuka_lwr4_description` since this is what the label on the robot says, which is less confusing. I would then add some info to the LWR3 origin.

**Comment by christian-rauch** [comment]
The catkin package has the generic name `lwr_defs`. Should we also rename the catkin package to `kuka_lwr4_description`? This will break a couple of packages but will prevent name conflicts with other lwr definitions.

**Comment by VladimirIvan** [comment]
Yes, the package name should match. We then need to propagate the changes to the dependant packages.

**Comment by christian-rauch** [comment]
@wxmerkt Can this be closed?
